{{- if .Values.metricsService.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "typesense-operator.fullname" . }}-controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
  {{- include "typesense-operator.labels" . | nindent 4 }}
  {{- if .Values.metricsService.serviceMonitor.release }}
    release: {{ .Values.metricsService.serviceMonitor.release | quote }}
  {{- end }}
  {{- with .Values.metricsService.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metricsService.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      {{- with .Values.metricsService.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metricsService.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.metricsService.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metricsService.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "typesense-operator.selectorLabels" . | nindent 6 }}
{{- end }}
