apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: typesense-local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-common-bootstrap-key
type: Opaque
data:
  typesense-api-key: SXdpVG9CcnFYTHZYeTJNMG1TS1hPaGt0dlFUY3VWUloxc1M5REtsRUNtMFFwQU93R1hoanVIVWJLQnE2ejdlSQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: c-kind-1-server-configuration
data:
  TYPESENSE_HEALTHY_READ_LAG: "1000"
  TYPESENSE_HEALTHY_WRITE_LAG: "500"
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-kind-1
spec:
  image: typesense/typesense:30.2.rc12-amd64
  replicas: 3
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "100m"
      memory: "64Mi"
  storage:
    size: 150Mi
    storageClassName: typesense-local-path
  adminApiKey:
    name: typesense-common-bootstrap-key
  metrics:
    logLevel: -4
    release: promstack
  additionalServerConfiguration:
    name: c-kind-1-server-configuration
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-kind-2
spec:
  image: typesense/typesense:30.0.rc29-amd64
  replicas: 3
  storage:
    size: 150Mi
    storageClassName: typesense-local-path
  adminApiKey:
    name: typesense-common-bootstrap-key
#  scrapers:
#    - name: docs-example-com
#      host: arch.otc-service.com
#      schedule: '*/2 * * * *'
  metrics:
    release: promstack
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-kind-3
spec:
  image: typesense/typesense:30.2
  replicas: 3
  storage:
    size: 150Mi
    storageClassName: typesense-local-path
  adminApiKey:
    name: typesense-common-bootstrap-key
  scrapers:
    - name: docs-example-com
      host: arch.otc-service.com
      schedule: '*/2 * * * *'
  metrics:
    release: promstack