name: TMDC Helm chart push workflow to AWS ECR

on:
  push:
    tags:
      - '*[0-9]+.*[0-9]+.*[0-9]-d*'

jobs:
# For RELEASE

  dev-release:
    name: Release Package and Push Helm Chart to ECR
    runs-on: ubuntu-latest
    container:
        image: tmdcio/k8s_cli_builder:0.7.0
        credentials:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    permissions:
      id-token: write
      contents: read
    
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-d')
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_ECR_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Configure Git safe directory
      run: git config --global --add safe.directory /__w/cert-manager/cert-manager

    - name: Install rsync
      run: apt-get update && apt-get install -y rsync
      
    - name: Package and push Helm chart
      env:
        TAG: ${{ github.ref_name }}
        ECR_HOST: ${{ steps.login-ecr.outputs.registry }}
      run: |
          make push-oci-chart